### ISSUE TITLE
After upgrade, @sveltejs/kit postinstall will never finish

### ISSUE THREAD

**Issue by vai** [kwchang0831/svelte-QWER#76]
### Describe the bug

When installing on Windows, the svelte-kit postInstall step hangs indefinitely, and will eventually run out of memory and crash.

### Logs

```shell

; pnpm i
Scope: all 2 workspace projects
Lockfile is up to date, resolution step is skipped
Packages: +880
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Progress: resolved 880, reused 880, downloaded 0, added 0, done

node_modules/.pnpm/sharp@0.32.1/node_modules/sharp: Running install script, done in 521ms
node_modules/.pnpm/svelte-preprocess@5.0.4_postcss@8.4.24_sass@1.63.6_svelte@4.0.0_typescript@5.1.3/node_modules/svelte-preprocess: Running postinstall script, done in 19ms
node_modules/.pnpm/esbuild@0.17.18/node_modules/esbuild: Running postinstall script, done in 200ms
node_modules/.pnpm/@sveltejs+kit@1.20.5_svelte@4.0.0_vite@4.3.9/node_modules/@sveltejs/kit: Running postinstall script, failed in 12m 48.2s
.../node_modules/@sveltejs/kit postinstall$ node postinstall.js
└─ Failed in 12m 48.2s at C:\dev\qwrk\asdf.qwrk.dev\node_modules\.pnpm\@sveltejs+kit@1.20.5_svelte@4.0.0_vite@4.3.9\node_modules\@sveltejs\kit
`
```

### System Info

```shell
System:
    OS: Windows 10 10.0.25290
    CPU: (24) x64 AMD Ryzen 9 3900X 12-Core Processor
    Memory: 28.55 GB / 63.91 GB
  Binaries:
    Node: 20.4.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 9.4.1 - C:\Program Files\nodejs\npm.CMD
    pnpm: 8.6.6 - ~\AppData\Local\pnpm\pnpm.CMD
  Browsers:
    Chrome: 114.0.5735.199
    Edge: Spartan (44.25290.1010.0), Chromium (114.0.1823.43), ChromiumDev (116.0.1938.16)
    Internet Explorer: 11.0.25290.1000
  npmPackages:
    @sveltejs/adapter-netlify: 2.0.7 => 2.0.7
    @sveltejs/adapter-node: 1.2.4 => 1.2.4
    @sveltejs/adapter-static: 2.0.2 => 2.0.2
    @sveltejs/adapter-vercel: 3.0.1 => 3.0.1
    @sveltejs/kit: 1.20.5 => 1.20.5
    svelte: ^4.0.0 => 4.0.0
    vite: ^4.3.9 => 4.3.9
`


### Additional Information

_No response_

**Comment by kwchang0831** [comment]
Not only on Windows, it also happens on Linux. I have upgraded the deps, but does not seem to help.

Update to the latest, and use `--ignore-scripts` flag for pnpm for now.

```
pnpm i --ignore-scripts
```

**Comment by jinzhijie** [comment]
> 



> Not only on Windows, it also happens on Linux. I have upgraded the deps, but does not seem to help.
> 
> Update to the latest, and use `--ignore-scripts` flag for pnpm for now.
> 
> ```
> pnpm i --ignore-scripts
> ```

I'v got the same problem.

I've tried to follow your instruction. However, when I run `pnpm build` it throws errors below. 😢

```
> @kwchang0831/svelte-qwer@0.11.0 build:i18n /example.com-qwer
> npx typesafe-i18n --no-watch

[typesafe-i18n] version 5.25.1
[typesafe-i18n] generating files for TypeScript version: '5.1.x'
[typesafe-i18n] options: { adapter: 'svelte', esmImports: true }
[typesafe-i18n] generated file: './src/i18n/i18n-types.ts'
[typesafe-i18n] ... all files are up to date
[typesafe-i18n] generating files completed

> @kwchang0831/svelte-qwer@0.11.0 build:partytown /example.com-qwer
> partytown copylib static/~partytown

Partytown lib copied to: /example.com-qwer/static/~partytown

> @kwchang0831/svelte-qwer@0.11.0 build:sveltekit /example.com-qwer
> vite build

▲ [WARNING] Cannot find base config file "./.svelte-kit/tsconfig.json" [tsconfig.json]

    tsconfig.json:2:13:
      2 │   "extends": "./.svelte-kit/tsconfig.json",
        ╵              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

failed to load config from /example.com-qwer/vite.config.js
error during build:
Error: 
Something went wrong installing the "sharp" module

Cannot find module '../build/Release/sharp-linuxmusl-x64.node'
Require stack:
- /example.com-qwer/node_modules/.pnpm/sharp@0.32.4/node_modules/sharp/lib/sharp.js
- /example.com-qwer/node_modules/.pnpm/sharp@0.32.4/node_modules/sharp/lib/constructor.js
- /example.com-qwer/node_modules/.pnpm/sharp@0.32.4/node_modules/sharp/lib/index.js

Possible solutions:
- Install with verbose logging and look for errors: "npm install --ignore-scripts=false --foreground-scripts --verbose sharp"
- Install for the current linuxmusl-x64 runtime: "npm install --platform=linuxmusl --arch=x64 sharp"
- Consult the installation documentation: https://sharp.pixelplumbing.com/install
    at Object.<anonymous> (/example.com-qwer/node_modules/.pnpm/sharp@0.32.4/node_modules/sharp/lib/sharp.js:37:9)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at Module.load (node:internal/modules/cjs/loader:1119:32)
    at Module._load (node:internal/modules/cjs/loader:960:12)
    at Module.require (node:internal/modules/cjs/loader:1143:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at Object.<anonymous> (/example.com-qwer/node_modules/.pnpm/sharp@0.32.4/node_modules/sharp/lib/constructor.js:11:1)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
 ELIFECYCLE  Command failed with exit code 1.
ERROR: "build:sveltekit" exited with 1.
 ELIFECYCLE  Command failed with exit code 1.
```

**Comment by jinzhijie** [comment]
**GOOD NEWS**

I've found a temporary solutions.

```bash
# sharp and sharp-libvips prebuilt binaries
# dont need node-gyp
export npm_config_sharp_binary_host=https://npmmirror.com/mirrors/sharp
export npm_config_sharp_libvips_binary_host=https://npmmirror.com/mirrors/sharp-libvips

pnpm i

# then it can works
pnpm dev
# or
pnpm build
```
---

During the installation process, I noticed that the root cause of this issue lies in the post-install script of `@sveltejs\kit` is stuck by the install script of `sharp`!!!

So I set [2 environments](https://sharp.pixelplumbing.com/install#chinese-mirror) to use the prebuilt binaries of `sharp`. While the install script of `sharp` runs successfully, the post-install script of `@sveltejs\kit` will finish as well.

**Comment by kwchang0831** [comment]
I have faced the same problem with sharp installation.
I searched for a couple of hours and could not find any solid solution for both Windows and Linux.
I tried to clean up
```sh
rm node_modules QWER/node_modules -rf
rm pnpm-lock.yaml
```
And included Sharp in the devDependencies. 
It seemed to work. 
(I do vercel build locally and deploy pre-built to the production. I assumed just do deploy might not work, the "sharp" module installation error will probably show up.)

Thanks for your temporary solution @jinzhijie.

**Comment by vai** [comment]
I can confirm that I removed the node\_modules and lock file, then ran   
`pnpm i -d sharp -w` and `pnpm dev` and `pnpm build` and `pnpm preview` now succeed.

**Comment by vai** [comment]
Didn't mean to close the issue (tab to next field should hit comment, not close!)  
  
The sharp dependency is now in devDependencies though, so this should likely be closed, but I don't know your process.

**Comment by kwchang0831** [comment]
If you feel the issue is resolved for you, feel free to close :D
If you let me decide, I will keep it open for now... So I will make sure I remember to investigate this issue again later in the future to see if the issue is still there.

**Comment by vai** [comment]
Works for me.
