### ISSUE TITLE
build error due to PrismJS

### ISSUE THREAD

**Issue by michaelhauser** [kwchang0831/svelte-QWER#94]
### Describe the bug

Attempt to build on MacOS fails.

### Logs

```shell
(base) michael@MichaelacStudio qwer % pnpm dev

> @kwchang0831/svelte-qwer@0.12.0 dev /Users/michael/Documents/dev/qwer
> npm-run-all -s build:QWER dev:watch


> @kwchang0831/svelte-qwer@0.12.0 build:QWER /Users/michael/Documents/dev/qwer
> node --no-warnings QWER build

/Users/michael/Documents/dev/qwer/node_modules/.pnpm/prismjs@1.29.0/node_modules/prismjs/prism.js:345
					lang[key] = redef[key];
					          ^

TypeError: Cannot set properties of undefined (setting 'class-name')
    at Object.extend (/Users/michael/Documents/dev/qwer/node_modules/.pnpm/prismjs@1.29.0/node_modules/prismjs/prism.js:345:16)
    at /Users/michael/Documents/dev/qwer/node_modules/.pnpm/prismjs@1.29.0/node_modules/prismjs/components/prism-cpp.min.js:1:856
    at Object.<anonymous> (/Users/michael/Documents/dev/qwer/node_modules/.pnpm/prismjs@1.29.0/node_modules/prismjs/components/prism-cpp.min.js:1:2589)
    at Module._compile (node:internal/modules/cjs/loader:1376:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
    at Module.load (node:internal/modules/cjs/loader:1207:32)
    at Module._load (node:internal/modules/cjs/loader:1023:12)
    at cjsLoader (node:internal/modules/esm/translators:345:17)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/translators:294:7)
    at ModuleJob.run (node:internal/modules/esm/module_job:218:25)

Node.js v20.10.0
 ELIFECYCLE  Command failed with exit code 1.
ERROR: "build:QWER" exited with 1.
 ELIFECYCLE  Command failed with exit code 1.
```

### System Info

```shell
System:
    OS: macOS 13.5
    CPU: (12) arm64 Apple M2 Max
    Memory: 145.84 MB / 96.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.10.0 - /usr/local/bin/node
    Yarn: 1.22.21 - /usr/local/bin/yarn
    npm: 10.2.5 - /usr/local/bin/npm
    pnpm: 8.12.1 - /usr/local/bin/pnpm
  npmPackages:
    @sveltejs/adapter-cloudflare: ^2.3.3 => 2.3.3
    @sveltejs/adapter-netlify: 2.0.8 => 2.0.8
    @sveltejs/adapter-node: 1.3.1 => 1.3.1
    @sveltejs/adapter-static: 2.0.3 => 2.0.3
    @sveltejs/adapter-vercel: 3.0.3 => 3.0.3
    @sveltejs/kit: 1.27.3 => 1.27.3
    svelte: ^4.2.2 => 4.2.2
    vite: ^4.5.0 => 4.5.0
```

**Comment by Creative-Difficulty** [comment]
works on M2 pro macbook for me

**Comment by kwchang0831** [comment]
I have observed the issue before.
I just simply ran the `pnpm dev` command again, and then the problem was gone.

I will close this issue for now. If the thing gets worse, we can investigate more.
